version: '3.8'

services:
    lib:
        image: fastify-knex-api-lib
        build: 
            context: ../
            dockerfile: docker/lib/Dockerfile
            args:
                - IDIR=fastify-knex-api
                #- BMODE=production # default development on Dockerfile
        volumes:
            - ../:/ws/fastify-knex-api:cached
            # node_modules in un volume temporaneo che non mi sovraccarica il prj reale in debug
            - lib-modules:/ws/fastify-knex-api/node_modules 
        environment:
            - CRUD_CLIENT=mysql2
            - CRUD_DB_URI=mysql://root:test@mariadb:3306/test

        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity
        deploy:
            resources:
                limits:
                    cpus: "2"
    mariadb:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
        ports:
            - 5100:3306
        hostname: mariadb
        volumes:
            - ../test/seed/maria.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
    lib-modules:

networks:
    default:
        name: docker_default
        external: true
