name: coverage
# on: [push, pull_request, workflow_dispatch] # disabled for debug
on: [workflow_dispatch]
jobs:
  coveralls:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: npm install
        run: npm install
      - name: docker ps
        run: docker ps -a
      - name: copy db test script
        run: DID=$(docker ps --format "{{.ID}}") && docker cp  test/seed/maria.sql "$DID":/tmp
      - name: ls
        run: DID=$(docker ps --format "{{.ID}}") && docker exec "$DID" ls /tmp
      - name: create db test
        run: DID=$(docker ps --format "{{.ID}}") && docker exec "$DID" /bin/bash -c 'mariadb -uroot -ptest test < /tmp/maria.sql'
      - name: npm run test
        run: npm run test
        env:
          CRUD_CLIENT: mysql2
          CRUD_DB_URI: mysql://root:test@mariadb/test
      #- name: coveralls
      #  uses: coverallsapp/github-action@master
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
